packages:
  # specify a package in a direct subdir of the root
  #- "my-app"
  # all packages in direct subdirs of packages/
  - "apps/*"
  # all packages in subdirs of components/
  #- "components/**"
  # exclude packages that are inside test directories
  #- "!**/test/**"

  # Define a catalog of version ranges.
catalog:
  react: "^18.3.1"
  react-dom: "^18.3.1"
